### ISSUE TITLE
Failed to load image on resolve type

### ISSUE THREAD

**Issue by zexron** [danielhusar/styled-jsx-url-loader#2]
Hi, I'm meeting an issue. When setting type as `resolve` from external stylesheet file, the image will not solved and leave it as is in style config. 
Demo code as below:
**test.scss**
```scss
/* @styled-jsx=resolve */
div {
  background: url(./someimage.png);
}
```
**test.jsx**
```javascript
import style from './test.scss';
export default function Comp() {
  return (
    <>
      {style.styles}
      <div className={style.className} />
    </>
  );
}
```
